### ISSUE TITLE
error : python train_segmentation.py --model='unet'

### ISSUE THREAD

**Issue by NguyenDangBinh** [TianzhongSong/Person-Segmentation-Keras#15]
dear,
Epoch 1/50
Traceback (most recent call last):
  File "train_segmentation.py", line 102, in <module>
    main()
  File "train_segmentation.py", line 90, in main
    callbacks=[checkpoint],
  File "/home/vsmart/anaconda3/envs/tensorflow/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/vsmart/anaconda3/envs/tensorflow/lib/python3.7/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/vsmart/anaconda3/envs/tensorflow/lib/python3.7/site-packages/keras/engine/training_generator.py", line 181, in fit_generator
    generator_output = next(output_generator)
  File "/home/vsmart/anaconda3/envs/tensorflow/lib/python3.7/site-packages/keras/utils/data_utils.py", line 709, in get
    six.reraise(*sys.exc_info())
  File "/home/vsmart/anaconda3/envs/tensorflow/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/vsmart/anaconda3/envs/tensorflow/lib/python3.7/site-packages/keras/utils/data_utils.py", line 685, in get
    inputs = self.queue.get(block=True).get()
  File "/home/vsmart/anaconda3/envs/tensorflow/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/home/vsmart/anaconda3/envs/tensorflow/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/vsmart/anaconda3/envs/tensorflow/lib/python3.7/site-packages/keras/utils/data_utils.py", line 626, in next_sample
    return six.next(_SHARED_SEQUENCES[uid])
  File "/home/vsmart/Person-Segmentation-Keras/utils/segdata_generator.py", line 62, in generator
    root_path, n_classes, input_height, input_width)
  File "/home/vsmart/Person-Segmentation-Keras/utils/segdata_generator.py", line 21, in get_batch
    if img.shape[0] >= img.shape[1]:
AttributeError: 'NoneType' object has no attribute 'shape'

Can you show me the error?
Thank you

**Comment by shikaihaha** [comment]
There is a problem with the image path，no images  is loaded
