### ISSUE TITLE
'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Chancetc** [TianzhongSong/Person-Segmentation-Keras#16]
I downloaded humanparsing assets and place it in the same directory with train_segmentation.py, but this error still occur! Does anyone know the reason? plz~!

**Comment by Chancetc** [comment]
Traceback (most recent call last):
  File "/Users/chanceguo/PycharmProjects/personSegment/train_segmentation.py", line 103, in <module>
    main()
  File "/Users/chanceguo/PycharmProjects/personSegment/train_segmentation.py", line 91, in main
    callbacks=[checkpoint],
  File "/Users/chanceguo/PycharmProjects/personSegment/venv/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/Users/chanceguo/PycharmProjects/personSegment/venv/lib/python2.7/site-packages/keras/engine/training.py", line 1658, in fit_generator
    initial_epoch=initial_epoch)
  File "/Users/chanceguo/PycharmProjects/personSegment/venv/lib/python2.7/site-packages/keras/engine/training_generator.py", line 181, in fit_generator
    generator_output = next(output_generator)
  File "/Users/chanceguo/PycharmProjects/personSegment/venv/lib/python2.7/site-packages/keras/utils/data_utils.py", line 733, in get
    six.reraise(*sys.exc_info())
  File "/Users/chanceguo/PycharmProjects/personSegment/venv/lib/python2.7/site-packages/keras/utils/data_utils.py", line 702, in get
    inputs = future.get(timeout=30)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by Chancetc** [comment]
not placed in the correct path
